### ISSUE TITLE
Erroneous type parameter on HttpApi::create_dm

### ISSUE THREAD

**Issue by ThatsNoMoon** [mbenoukaiss/automate#5]
[HttpApi::create_dm](https://github.com/mbenoukaiss/automate/blob/master/src/http/mod.rs#L322) has a type parameter that is unused. Its signature should probably either not have the type parameter at all or use `recipient: S`?

**Comment by mbenoukaiss** [comment]
Exactly, I just copied another endpoint without paying too much attention. I removed the need to manually create a Recipient object and make the function take `recipient: S` in commit 0015bba6464444aadccf8126fffa6ffff98e7938
